AllCops:
  TargetRubyVersion: 3.3

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/VariableInterpolation:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Lint/RescueException:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics:
  Enabled: false
