AllCops:
  TargetRubyVersion: 3.3

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/VariableInterpolation:
  Enabled: false

Style/Semicolon:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false
