#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative 'lib/hdl'
require_relative 'lib/rtlil'

Top = HDL.module do
  x = io(:out)
  y = io(:out)

  counter = reg(16, reset: -2)
  counter =~ counter + 1

  x =~ counter[-1]

  y_reg = reg
  iff(counter.zero?) { y_reg =~ !y_reg }
  y =~ y_reg
end

Top.dump
puts

Top.dump_rtlil
